package org.tat.fni.api.common;

public class TableName {
	public static final String VWT_MEDICALCLAIM_INITIALREPROT_VIEW = "VWT_MEDICALCLAIM_INITIALREPROT_VIEW";
	public static final String VWT_MEDICALCLAIM_PAYMENTREPROT_VIEW = "VWT_MEDICALCLAIM_PAYMENTREPROT_VIEW";
	public static final String DISABILITY_CLAIM_ICD = "DISABILITY_CLAIM_ICD";
	public static final String OPERATION_CLAIM_ICD = "OPERATION_CLAIM_ICD";
	public static final String PERSONPRODUCTHISTORY = "PERSONPRODUCTHISTORY";
	public static final String MEDICALPERSONHISTORYRECORD = "MEDICALPERSONHISTORYRECORD";
	public static final String BANK = "BANK";
	public static final String CLASSOFINSURANCE = "CLASSOFINSURANCE";
	public static final String COA = "COA";
	public static final String CCOA = "CCOA";
	public static final String TRANTYPE = "TRANTYPE";
	public static final String MANUFACTURE = "MANUFACTURER";
	public static final String ADDON = "ADDON";
	public static final String MOTORPROPOSALWORKFLOW = "MOTORPROPOSALWORKFLOW";
	public static final String CLASSVALUE = "CLASSVALUE";
	public static final String BUILDINGCLASS = "BUILDINGCLASS";
	public static final String PAEBUILDINGCLASS = "PAEBUILDINGCLASS";
	public static final String TOWNSHIP = "TOWNSHIP";
	public static final String DISTRICT = "DISTRICT";
	public static final String RELATIONSHIP = "RELATIONSHIP";
	public static final String COMPANY = "COMPANY";
	public static final String COINSURNACE_COMPANY = "COINSURNACE_COMPANY";
	public static final String COINSURNACE = "COINSURNACE";
	public static final String COINSURNACE_PRODUCT_GROUP = "COINSURNACE_PRODUCT_LINK";
	public static final String ORGANIZATION = "ORGANIZATION";
	public static final String CUSTOMER = "CUSTOMER";
	public static final String WALL = "WALL";
	public static final String FLOOR = "FLOOR";
	public static final String OCCUPATION = "OCCUPATION";
	public static final String COUNTRY = "COUNTRY";
	public static final String HOSPITAL = "HOSPITAL";
	public static final String MOTORTYPE = "MOTORTYPE";
	public static final String KEYFACTOR = "KEYFACTOR";
	public static final String BRANCH = "BRANCH";
	public static final String ROOF = "ROOF";
	public static final String AGENT = "AGENT";
	public static final String AGENTPORTFOLIO = "AGENTPORTFOLIO";
	public static final String AGENT_ATTACH_LINK = "AGENT_ATTACH_LINK";
	public static final String PAYMENTTYPE = "PAYMENTTYPE";
	public static final String PROVINCE = "PROVINCE";
	public static final String CITY = "CITY";
	public static final String INITIAL = "INITIAL";
	public static final String TYPEOFBODY = "TYPEOFBODY";
	public static final String CASHINTRANSITPROPOSAL = "CASHINTRANSITPROPOSAL";
	public static final String CASHINTRANSITKEYFACTORVALUE = "CASHINTRANSIT_KEYFACTORVALUE_LINK";
	public static final String CASHINTRANSITPROPOSALATTACHMENT = "CASHINTRANSITPROPOSAL_ATTACHMENT";
	public static final String CASHINSAFEPROPOSAL = "CASHINSAFEPROPOSAL";
	public static final String FIDELITYPROPOSALATTACHMENT = "FIDELITYPROPOSALATTACHMENT";
	public static final String FIDELITYPROPOSAL = "FIDELITYPROPOSAL";
	public static final String FIDELITYPROPOSALINFO = "FIDELITYPROPOSALINFO";
	public static final String FIDELITYINFO = "FIDELITYINFO";
	public static final String FIDELITYPOLICYKEYFACTORVALUE = "FIDELITYPOLICYKEYFACTORVALUE";
	public static final String FIDELITYKEYFACTORVALUE = "FIDELITY_KEYFACTORVALUE_LINK";
	public static final String CASHINSAFEPROPOSALATTACHMENT = "CASHINSAFEPROPOSAL_ATTACHMENT";
	public static final String CASHINSAFEKEYFACTORVALUE = "CASHINSAFE_KEYFACTORVALUE_LINK";
	public static final String APPROVAL = "APPROVAL";
	public static final String SURVEY = "SURVEY";
	public static final String RESOURCEITEM = "WEBPAGE";
	public static final String USER = "USERS";
	public static final String MOBILEUSER = "MOBILEUSERS";
	public static final String USERROLE = "USERROLE";
	public static final String WEBPAGE = "WEBPAGE";
	public static final String BUILDINGOCCUPATION = "BUILDINGOCCUPATION";
	public static final String ADJOININGBUILDINGINFO = "ADJOININGBUILDINGINFO";
	public static final String FIREPROPOSALSIDETAIL = "FIREPROPOSALSIDETAIL";
	public static final String USER_AUTHORITY = "USER_AUTHORITY";
	public static final String PAYMENT = "PAYMENT";
	public static final String DENOPAYMENT = "DENOPAYMENT";
	public static final String AGENTCOMMISSION = "AGENTCOMMISSION";
	public static final String CUR = "CUR";
	public static final String QUALIFICATION = "QUALIFICATION";
	public static final String RELIGION = "RELIGION";
	public static final String INDUSTRY = "INDUSTRY";
	public static final String BANKBRANCH = "BANKBRANCH";
	public static final String WORKFLOW = "WORKFLOW";
	public static final String WORKFLOW_HIST = "WORKFLOW_HIST";
	public static final String TASKMESSAGE = "WORKFLOW_TASKMESSAGE";
	public static final String SALEMAN = "SALEMAN";
	public static final String CASHIER = "CASHIER";
	public static final String YCDCCITY = "YCDCCITY";
	public static final String RISKYOCCUPATION = "RISKYOCCUPATION";

	public static final String DECLARATION_POLICY_COLLECTION = "DECLARATION_POLICY_COLLECTION";
	public static final String DECLARATION_POLICY_COLLECTION_HISTORY = "DECLARATION_POLICY_COLLECTION_HISTORY";
	public static final String DECLARATION_PROPOSAL = "DECLARATION_PROPOSAL";
	public static final String MONTHLY_DECLARATION_POLICY = "MONTHLY_DECLARATION_POLICY";

	public static final String AGENT_ATTACHMENT = "AGENT_ATTACH_LINK";
	public static final String TLF = "TLF";
	public static final String INTERFACE_FILE = "INTERFACE_FILE";
	public static final String INTERFACE_FILE_HISTORY = "INTERFACE_FILE_HISTORY";
	public static final String INTERFACE_FILE_TLF_REF = "INTERFACE_FILE_TLF_REF";
	public static final String INTERFACE_FILE_HIST_TLF_REF = "INTERFACE_FILE_HIST_TLF_REF";
	public static final String TLF_CONVERSION_FORMAT = "TLF_CONVERSION_FORMAT";
	public static final String TLF_CONVERSION_FORMAT_ACNAME = "TLF_CONVERSION_FORMAT_ACNAME";
	public static final String TLF_CONVERSION_FORMAT_PAIRED_KEY = "TLF_CONVERSION_FORMAT_PAIRED_KEY";
	public static final String CHECKOFACCOUNT = "CHECKOFACCOUNT";
	public static final String ACCEPTEDINFO = "ACCEPTEDINFO";
	public static final String CLAIMACCEPTEDINFO = "CLAIMACCEPTEDINFO";
	public static final String COASETUP = "COASETUP";
	public static final String CASHDENO = "CASHDENO";
	public static final String CLAIMINFO = "CLAIMINFO";
	public static final String TYPESOFSPORT = "TYPESOFSPORT";
	public static final String WORKSHOP = "WORKSHOP";
	public static final String SURVEYMEMBER = "SURVEYMEMBER";
	public static final String SURVEYTEAM = "SURVEYTEAM";
	public static final String AFP_PRODUCT_DISCOUNTRATE_LINK = "AFP_PRODUCT_DISCOUNTRATE_LINK";
	public static final String CASHINSAFEACCEPTEDINFO = "CASHINSAFEACCEPTEDINFO";
	/* CoInsurance */
	public static final String COINSURANCE = "COINSURANCE";
	public static final String COINSURANCE_COMPANY = "COINSURANCE_COMPANY";
	public static final String COINSURANCE_PRODUCT_GROUP = "COINSURANCE_PRODUCT_LINK";
	public static final String COINSURANCE_ATTACH_LINK = "COINSURANCE_ATTACH_LINK";
	public static final String COINSURANCE_FIREPOLICY_LINK = "COINSURANCE_FIREPOLICY_LINK";
	public static final String COINSURANCE_MOTORPOLICY_LINK = "COINSURANCE_MOTORPOLICY_LINK";
	public static final String COINSURANCECLAIM = "COINSURANCECLAIM";
	public static final String COINSURANCE_RATIO = "COINSURANCE_RATIO";
	public static final String COINSURANCE_DETAIL_RATIO = "COINSURANCE_DETAIL_RATIO";
	public static final String REINSURANCE_RATIO = "REINSURANCE_RATIO";
	public static final String REINSURANCE_DETAIL_RATIO = "REINSURANCE_DETAIL_RATIO";

	/* Reinsurance */
	public static final String REINSURANCE = "REINSURANCE";

	/* Product */
	public static final String PRODUCT = "PRODUCT";
	public static final String PRODUCT_PREMIUMRATE = "PRODUCT_PREMIUMRATE_LINK";
	public static final String PRODUCT_RATEKEYFACTOR = "PRODUCT_RATEKEYFACTOR";
	public static final String PRODUCTGROUP = "PRODUCTGROUP";
	public static final String PRODUCTCONTENT = "PRODUCTCONTENT";
	public static final String PRODUCT_DISABILITYPART = "PRODUCT_DISABILITYPART";
	public static final String PRODUCT_DISABILITYRATE = "PRODUCT_DISABILITYRATE";

	/* bmi */
	public static final String BMICHART = "BMICHART";

	/* Motor Proposal */
	public static final String MPROPOSAL_VEHICLE_DRIVER_LINK = "MPROPOSAL_VEHICLE_DRIVER_LINK";
	public static final String MOTORPROPOSAL = "MOTORPROPOSAL";
	public static final String MOTORPROPOSALATTACHMENT = "MPROPOSAL_ATTACH_LINK";
	public static final String MOTORSURVEY = "MPROPOSAL_SURVEY_LINK";
	public static final String PROPOSALVEHICLE = "MPROPOSAL_VEHICLE_LINK";
	public static final String VEHKEYFACTORVALUE = "MPROPOSAL_VEHICLE_KEYFACTORVALUE_LINK";
	public static final String VEHADDON = "MPROPOSAL_VEHICLE_ADDON_LINK";
	public static final String VEHICLEATTACHMENT = "MPROPOSAL_VEHICLE_ATTACH_LINK";
	public static final String MPROPOSAL_VEHICLE_OTHERRISK = "MPROPOSAL_VEHICLE_OTHERRISK_LINK";
	public static final String MPROPOSAL_VEHICLE_INSUREDRECORD = "MPROPOSAL_VEHICLE_INSUREDRECORD";

	/* Motor Proposal History */
	public static final String MPROPOSAL_VEHICLE_DRIVER_HISTORY = "MPROPOSAL_VEHICLE_DRIVER_HISTORY";
	public static final String MOTORPROPOSALHISTORY = "MOTORPROPOSAL_HISTORY";
	public static final String MOTORPROPOSALATTACHMENTHISTORY = "MPROPOSAL_ATTACH_HISTORY";
	public static final String PROPOSALVEHICLEHISTORY = "MPROPOSAL_VEHICLE_HISTORY";
	public static final String VEHKEYFACTORVALUEHISTORY = "MPROPOSAL_VEHICLE_KEYFACTORVALUE_HISTORY";
	public static final String VEHADDONHISTORY = "MPROPOSAL_VEHICLE_ADDON_HISTORY";
	public static final String VEHICLEATTACHMENTHISTORY = "MPROPOSAL_VEHICLE_ATTACH_HISTORY";
	public static final String MPROPOSAL_VEHICLE_OTHERRISK_HISTORY = "MPROPOSAL_VEHICLE_OTHERRISK_HISTORY";
	public static final String MPROPOSAL_VEHICLE_INSUREDRECORD_HISTORY = "MPROPOSAL_VEHICLE_INSUREDRECORD_HISTORY";

	/* Motor Policy */
	public static final String MOTORPOLICY = "MOTORPOLICY";
	public static final String MPOLICY_VEHICLE_DRIVER_LINK = "MPOLICY_VEHICLE_DRIVER_LINK";
	public static final String MPOLICY_VEHICLE_LINK = "MPOLICY_VEHICLE_LINK";
	public static final String MOTORPOLICYATTACHMENT = "MPOLICY_ATTACH_LINK";
	public static final String POLICYVEHICLEATTACHMENT = "MPOLICY_VEHICLE_ATTACH_LINK";
	public static final String POLICYVEHADDON = "MPOLICY_VEHICLE_ADDON_LINK";
	public static final String POLICYVEHKEYFACTORVALUE = "MPOLICY_VEHICLE_KEYFACTORVALUE_LINK";
	public static final String MPOLICY_VEHICLE_OTHERRISK = "MPOLICY_VEHICLE_OTHERRISK_LINK";
	public static final String MPOLICY_VEHICLE_INSUREDRECORD = "MPOLICY_VEHICLE_INSUREDRECORD";

	/* Motor Policy history */
	public static final String MOTORPOLICYHISTORY = "MOTORPOLICY_HISTORY";
	public static final String MOTORPOLICY_HISTORY_DRIVERLIST_LINK = "MOTORPOLICY_HISTORY_DRIVERLIST_LINK";
	public static final String MPOLICYHISTORY_VEHICLE_LINK = "MPOLICY_HISTORY_VEHICLE_LINK";
	public static final String MOTORPOLICYHISTORYATTACHMENT = "MPOLICY_HISTORY_ATTACH_LINK";
	public static final String POLICYHISTORYVEHICLEATTACHMENT = "MPOLICY_HISTORY_VEHICLE_ATTACH_LINK";
	public static final String POLICYHISTORYVEHADDON = "MPOLICY_HISTORY_VEHICLE_ADDON_LINK";
	public static final String POLICYHISTORYVEHKEYFACTORVALUE = "MPOLICY_HISTORY_VEHICLE_KEYFACTORVALUE_LINK";
	public static final String MPOLICYHISTORY_VEHICLE_OTHERRISK = "MPOLICY_HISTORY_VEHICLE_OTHERRISK_LINK";
	public static final String MPOLICYHISTORY_VEHICLE_INSUREDRECORD = "MPOLICYHISTORY_VEHICLE_INSUREDRECORD";

	/* Motor Policy Edit history */
	public static final String MOTORPOLICYEDITHISTORY = "MOTORPOLICY_EDITHISTORY";
	public static final String MOTORPOLICY_EDITHISTORY_DRIVER = "MPOLICY_VEHILCE_HISTORY_DRIVERLIST_LINK";
	public static final String MPOLICYEDITHISTORY_VEHICLE_LINK = "MPOLICY_EDITHISTORY_VEHICLE";
	public static final String MOTORPOLICYEDITHISTORYATTACHMENT = "MPOLICY_EDITHISTORY_ATTACHMENT";
	public static final String POLICYEDITHISTORYVEHICLEATTACHMENT = "MPOLICY_EDITHISTORY_VEHICLE_ATTACHMENT";
	public static final String POLICYEDITHISTORYVEHADDON = "MPOLICY_EDITHISTORY_VEHICLE_ADDON";
	public static final String POLICYEDITHISTORYVEHKEYFACTORVALUE = "MPOLICY_EDITHISTORY_VEHICLE_KEYFACTORVALUE";
	public static final String MPOLICYEDITHISTORY_VEHICLE_OTHERRISK = "MPOLICY_EDITHISTORY_VEHICLE_OTHERRISK_LINK";
	public static final String MPOLICYEDITHISTORY_VEHICLE_INSUREDRECORD = "MPOLICYEDITHISTORY_VEHICLE_INSUREDRECORD";

	/* Life Proposal */
	public static final String LIFESURVEY = "LPROPOSAL_SURVEY_LINK";
	public static final String LIFEPROPOSAL = "LIFEPROPOSAL";
	public static final String LIFEPROPOSALTEMP = "LIFEPROPOSAL_TEMP";
	public static final String PROPOSALINSUREDPERSON = "LIFEPROPOSAL_INSUREDPERSON_LINK";
	public static final String LIFEPROPOSALATTACHMENT = "LIFEPROPOSAL_ATTACH_LINK";
	public static final String INSUREDPERSONADDON = "LIFEPROPOSAL_INSUREDPERSON_ADDON_LINK";
	public static final String INSUREDPERSONBENEFICIARIES = "INSUREDPERSON_BENEFICIARIES_LINK";
	public static final String INSUREDPERSONKEYFACTORVALUE = "LIFEPROPOSAL_INSUREDPERSON_KEYFACTORVALUE_LINK";
	public static final String INSUREDPERSONATTACHMENT = "LIFEPROPOSAL_INSUREDPERSON_ATTACH_LINK";
	public static final String INSUREDPERSONPOLICYHISTORYRECORD = "INSUREDPERSONPOLICYHISTORYRECORD";

	/* Life Proposal History */
	public static final String LIFEPROPOSAL_HISTORY = "LIFEPROPOSAL_HISTORY";
	public static final String LIFEPROPOSAL_INSURED_PERSON_HISTORY = "LIFEPROPOSAL_INSURED_PERSON_HISTORY";
	public static final String LIFEPROPOSAL_ATTACHMENT_HISTORY = "LIFEPROPOSAL_ATTACHMENT_HISTORY";
	public static final String LIFEPROPOSAL_INSURED_PERSON_ADDON_HISTORY = "LIFEPROPOSAL_INSURED_PERSON_ADDON_HISTORY";
	public static final String LIFEPROPOSAL_INSURED_PERSON_BENEFICIARIES_HISTORY = "LIFEPROPOSAL_INSURED_PERSON_BENEFICIARIES_HISTORY";
	public static final String LIFEPROPOSAL_INSURED_PERSON_KEYFACTOR_VALUE_HISTORY = "LIFEPROPOSAL_INSURED_PERSON_KEYFACTOR_VALUE_HISTORY";
	public static final String LIFEPROPOSAL_INSURED_PERSON_ATTACHMENT_HISTORY = "LIFEPROPOSAL_INSURED_PERSON_ATTACHMENT_HISTORY";

	/* Life Policy */
	public static final String LIFEPOLICY = "LIFEPOLICY";
	public static final String LIFEPOLICYATTACHMENT = "LIFEPOLICY_ATTACH_LINK";
	public static final String LIFEPOLICYINSUREDPERSONATTACHMENT = "LIFEPOLICY_INSUREDPERSON_ATTACH_LINK";
	public static final String LIFEPOLICYINSUREDPERSONADDON = "LIFEPOLICY_INSUREDPERSON_ADDON_LINK";
	public static final String LIFEPOLICYINSUREDPERSONBENEFICIARIES = "LIFEPOLICY_INSUREDPERSON_BENEFICIARIES_LINK";
	public static final String LIFEPOLICYINSUREDPERSONKEYFACTOR = "LIFEPOLICY_INSUREDPERSON_KEYFACTORVALUE_LINK";
	public static final String LIFEPOLICYINSUREDPERSON = "LIFEPOLICY_INSUREDPERSON_LINK";
	public static final String LIFEPOLICYSUMMARY = "LIFEPOLICYSUMMARY";
	public static final String SPORTMANTRAVELABROAD = "SPORTMANTRAVELABROAD";

	/* Life Policy History */
	public static final String LIFEPOLICYHISTORY = "LIFEPOLICYHISTORY";
	public static final String LIFEPOLICYATTACHMENTHISTORY = "LPOLICYHISTORY_ATTACH_LINK";
	public static final String LIFEPOLICYINSUREDPERSONADDONHISTORY = "LPOLICY_INSU_ADDON_HISTORY_LINK";
	public static final String LIFEPOLICYINSUREDPERSONATTACHMENTHISTORY = "LPOLICY_INSU_ATTACH_HIS_LINK";
	public static final String LIFEPOLICYINSUREDPERSONBENEFICIARIESHISTORY = "LPOLICY_INSU_BENEFI_HISTORY";
	public static final String LIFEPOLICYINSUREDPERSONHISTORY = "LPOLICY_INSUPERSON_HISTORY";
	public static final String LIFEPOLICYINSUREDPERSONKEYFACTORHISTORY = "LPOLICY_INSU_KEYFACTOR_HISTORY";

	/* Life Policy EditHistory */
	public static final String LIFEPOLICYEDITHISTORY = "LIFEPOLICY_EDITHISTORY";
	public static final String LIFEPOLICYATTACHMENTEDITHISTORY = "LPOLICY_EDITHISTORY_ATTACHMENT";
	public static final String LIFEPOLICYINSUREDPERSONADDONEDITHISTORY = "LPOLICY_INSU_ADDON_EDITHISTORY";
	public static final String LIFEPOLICYINSUREDPERSONATTACHMENTEDITHISTORY = "LPOLICY_INSU_ATTACH_EDITHISTORY";
	public static final String LIFEPOLICYINSUREDPERSONBENEFICIARIESEDITHISTORY = "LPOLICY_INSU_BENEFI_EDITHISTORY";
	public static final String LIFEPOLICYINSUREDPERSONEDITHISTORY = "LPOLICY_INSUPERSON_EDITHISTORY";
	public static final String LIFEPOLICYINSUREDPERSONKEYFACTOREDITHISTORY = "LPOLICY_INSU_KEYFACTOR_EDITHISTORY";

	/* Fire Policy */
	public static final String FIREPOLICY = "FIREPOLICY";
	public static final String FIREPOLICYATTACHMENT = "FIREPOLICY_ATTACH_LINK";
	public static final String POLICYBUILDINGINFO = "FIREPOLICY_BUILDINGINFO_LINK";
	public static final String POLICYENVIRONMENTBUILDINGINFO = "FIREPOLICY_ENVIRONMENTBUILDINGINFO_LINK";
	public static final String FIREPOLICYPRODUCTINFO = "FIREPOLICY_PRODUCTINFO_LINK";
	public static final String FIREPOLICYADDON = "FIREPOLICY_ADDON_LINK";
	public static final String FIREPOLICYKEYFACTORVALUE = "FIREPOLICY_KEYFACTORVALUE_LINK";
	public static final String FPOLICY_BUILDING_ATTACH_LINK = "FIREPOLICY_BUILDINGINFO_ATTACH_LINK";
	public static final String FPOLICY_HISTORY_RECORD_LINK = "FIREPOLICY_INSU_RECORD_LINK";
	public static final String FPOLICY_INSURANCECOVER_LINK = "FIREPOLICY_INSURANCECOVER_LINK";
	public static final String FIREPOLICY_ENDORSEMENT_PRINT = "FIREPOLICY_ENDORSEMENT_PRINT";
	public static final String LIFEPOLICY_ENDORSEMENT_PRINT = "LIFEPOLICY_ENDORSEMENT_PRINT";

	/* Fire Declaration Policy */
	public static final String FIREDECLARATIONPOLICY = "FIREDECLARATIONPOLICY";
	public static final String FIREDECLARATIONPOLICY_STOCKINFO = "FIREDECLARATIONPOLICY_STOCKINFO";
	public static final String FIREDECLARATIONPOLICY_STOCKINFO_ATTACH_LINK = "FIREDECLARATIONPOLICY_STOCKINFO_ATTACH_LINK";

	/* Fire Proposal */
	public static final String FIREPROPOSAL = "FIREPROPOSAL";
	public static final String BUILDINGINFO = "BUILDINGINFO";
	public static final String FIREPROPOSALATTACHMENT = "FIREPROPOSALATTACHMENT";
	public static final String FIREPROPOSAL_INSU_RECORD_LINK = "FIREPROPOSAL_INSU_RECORD_LINK";
	public static final String INSURANCECOVER = "INSURANCECOVER";
	public static final String FPROPOSAL_BUILDING_ATTACH_LINK = "FPROPOSAL_BUILDING_ATTACH_LINK";
	public static final String ENVIRONMENTBUILDINGINFO = "ENVIRONMENTBUILDINGINFO";
	public static final String FIREPRODUCTINFO = "FIREPRODUCTINFO";
	public static final String FIREADDON = "FIREADDON";
	public static final String FIREKEYFACTORVALUE = "FIREKEYFACTORVALUE";
	public static final String FIRESURVEY = "FPROPOSAL_SURVEY_LINK";

	/* Fire Proposal History */
	public static final String FIREPROPOSAL_ADDON_HISTORY = "FIREPROPOSAL_ADDON_HISTORY";
	public static final String FIREPROPOSAL_ATTACHMENT_HISTORY = "FIREPROPOSAL_ATTACHMENT_HISTORY";
	public static final String FIREPROPOSAL_BUILDING_ATTACHMENT_HISTORY = "FIREPROPOSAL_BUILDING_ATTACHMENT_HISTORY";
	public static final String FIREPROPOSAL_BUILDING_INFO_HISTORY = "FIREPROPOSAL_BUILDING_INFO_HISTORY";
	public static final String FIREPROPOSAL_ENVIRONMENT_BUILDING_INFO_HISTORY = "FIREPROPOSAL_ENVIRONMENT_BUILDING_INFO_HISTORY";
	public static final String FIREPROPOSAL_HISTORY = "FIREPROPOSAL_HISTORY";
	public static final String FIREPROPOSAL_KEY_FACTOR_VALUE_HISTORY = "FIREPROPOSAL_KEY_FACTOR_VALUE_HISTORY";
	public static final String FIREPROPOSAL_PRODUCT_INFO_HISTORY = "FIREPROPOSAL_PRODUCT_INFO_HISTORY";

	/* Fire Policy History */
	public static final String FIREPOLICY_HISTORY = "FIREPOLICY_HISTORY";
	public static final String FIREPOLICY_HISTORY_ATTACHMENT = "FIREPOLICY_HISTORY_ATTACHMENT";
	public static final String FIREPOLICY_HISTORY_BUILDINGINFO = "FIREPOLICY_HISTORY_BUILDINGINFO";
	public static final String FIREPOLICY_HISTORY_ENVIRONMENTBUILDINGINFO = "FIREPOLICY_HISTORY_ENVIRONMENTBUILDINGINFO";
	public static final String FIREPOLICY_HISTORY_PRODUCTINFO = "FIREPOLICY_HISTORY_PRODUCTINFO";
	public static final String FIREPOLICY_HISTORY_ADDON = "FIREPOLICY_HISTORY_ADDON";
	public static final String FIREPOLICY_HISTORY_KEYFACTORVALUE = "FIREPOLICY_HISTORY_KEYFACTORVALUE";
	public static final String FIREPOLICY_HISTORY_BUILDING_ATTACH = "FIREPOLICY_HISTORY_BUILDING_ATTACH";
	public static final String FIREPOLICY_HISTORY_HISTORY_RECORD = "FIREPOLICY_HISTORY_HISTORY_RECORD";
	public static final String FIREPOLICY_HISTORY_INSURANCECOVER = "FIREPOLICY_HISTORY_INSURANCECOVER";

	/* Fire Policy Edit History */
	public static final String FIREPOLICY_EDITHISTORY = "FIREPOLICY_EDITHISTORY";
	public static final String FIREPOLICY_EDITHISTORY_ATTACHMENT = "FIREPOLICY_EDITHISTORY_ATTACHMENT";
	public static final String FIREPOLICY_EDITHISTORY_BUILDINGINFO = "FIREPOLICY_EDITHISTORY_BUILDINGINFO";
	public static final String FIREPOLICY_EDITHISTORY_ENVIRONMENTBUILDINGINFO = "FIREPOLICY_EDITHISTORY_ENVIRONMENTBUILDINGINFO";
	public static final String FIREPOLICY_EDITHISTORY_PRODUCTINFO = "FIREPOLICY_EDITHISTORY_PRODUCTINFO";
	public static final String FIREPOLICY_EDITHISTORY_ADDON = "FIREPOLICY_EDItHISTORY_ADDON";
	public static final String FIREPOLICY_EDITHISTORY_KEYFACTORVALUE = "FIREPOLICY_EDITHISTORY_KEYFACTORVALUE";
	public static final String FIREPOLICY_EDITHISTORY_BUILDING_ATTACH = "FIREPOLICY_EDITHISTORY_BUILDING_ATTACH";
	public static final String FIREPOLICY_HISTORY_EDITHISTORY_RECORD = "FIREPOLICY_HISTORY_EDITHISTORY_RECORD";
	public static final String FIREPOLICY_EDITHISTORY_INSURANCECOVER = "FIREPOLICY_EDITHISTORY_INSURANCECOVER";

	/* Claim */
	public static final String ATTACHMENT = "ATTACHMENT";
	public static final String ATTACHMENTHOLDER = "ATTACHMENTHOLDER";
	public static final String CLAIM = "CLAIM";
	public static final String CLAIMITEM = "CLAIMITEM";
	public static final String VEHICLEPART = "VEHICLEPART";

	/* Fire Claim */
	public static final String FIREINFORM = "FIREINFORM";
	public static final String FIRECLAIM = "FIRECLAIM";
	public static final String FIRECLAIMITEM = "FIRECLAIMITEM";
	public static final String FIRECLAIMDETAILS = "FIRECLAIMDETAILS";
	public static final String FIRECLAIMSURVEY = "FIRECLAIMSURVEY";
	public static final String FIRECLAIMSURVEYITEM = "FIRECLAIMSURVEYITEM";

	/* Motor Claim */
	public static final String CLAIMSURVEY = "CLAIMSURVEY";
	public static final String CLAIMNOTIFICATION = "CLAIM_NOTIFICATION";
	public static final String MOTORCLAIM = "MOTORCLAIM";
	public static final String DAMAGEDVEHICLE = "OWNEDAMAGED";
	public static final String THIRDPARTYPROPERTY = "THIRDPARTYPROPERTY";
	public static final String TOWING = "TOWING";
	public static final String WINDSCREEN = "WINDSCREEN";
	public static final String PERSONCASUALTY = "PERSONCASUALTY_INFO";
	public static final String MEDICALEXPENSE = "MEDICALEXPENSE";
	public static final String REINSTATEMENTINFO = "REINSTATEMENT_INFO";

	/* Cargo Claim */
	public static final String CARGOINFORM = "CARGOINFORM";
	public static final String CARGOCLAIM = "CARGOCLAIM";
	public static final String CARGOCLAIMSURVEY = "CARGOCLAIMSURVEY";
	public static final String CARGOCLAIMITEM = "CARGOCLAIMITEM";
	public static final String CARGOCLAIMDETAILS = "CARGOCLAIMDETAILS";
	public static final String CARGOCLAIMSURVEYITEM = "CARGOCLAIMSURVEYITEM";

	/* Setting Variable */
	public static final String SETTING_VARIABLE = "SETTING_VARIABLE";

	/* LIFECLAIM */
	public static final String LIFECLAIM = "LIFECLAIM";
	public static final String LIFECLAIM_AMOUNT = "LIFECLAIM_AMOUNT";
	public static final String LIFECLAIM_ATTACHMENT = "LIFECLAIM_ATTACH_LINK";
	public static final String LIFECLAIM_BENEFICIARY = "LIFECLAIM_BENEFICIARY_LINK";
	public static final String LIFECLAIM_INSUREDPERSON_ATTACHMENT = "LIFECLAIM_INSUREDPERSON_ATTACH_LINK";
	public static final String LIFECLAIM_INSUREDPERSON_BENEFICIARY_ATTACHMENT = "LIFECLAIM_INSUREDPERSON_BENEFICIARY_ATTACH_LINK";
	public static final String LIFECLAIM_DISABILITYPART_LINK = "LIFECLAIM_DISABILITYPART_LINK";
	public static final String LIFECLAIMPROPOSAL = "LIFECLAIMPROPOSAL";
	public static final String DISABILITYLIFECLAIM = "DISABILITYLIFECLAIM";
	public static final String LIFECLAIMNOTIFICATION = "LIFECLAIMNOTIFICATION";
	public static final String LIFEHOSPITALIZEDCLAIM = "LIFEHOSPITALIZEDCLAIM";
	public static final String LIFEDEATHCLAIM = "LIFEDEATHCLAIM";
	public static final String LIFEPOLICYCLAIM = "LIFEPOLICYCLAIM";
	public static final String LIFECALIMSURVEY = "LIFECALIMSURVEY";
	public static final String LIFECLAIMBENEFICIARYPERSON = "LIFECLAIMBENEFICIARYPERSON";
	public static final String LIFECLAIMPROPOSALATTACHMENT = "LIFECLAIMPROPOSALATTACHMENT";

	/* LIFE PREMIUM */
	// TODO
	public static final String LIFEPOLICYPREMIUM = "LIFEPOLICY_PREMIUM";
	public static final String LIFEPOLICYBILLING = "LIFEPOLICY_BILLING";
	public static final String WSVERSIONREF = "WS_VERSION_REF";

	/* Motor Endorsement */
	public static final String MOTOR_ENDORSE_INFO = "MOTOR_ENDORSE_INFO";
	public static final String MOTOR_ENDORSE_VEHICLE = "MOTOR_ENDORSE_VEHICLE";
	public static final String MOTOR_ENDORSE_CHANGE = "MOTOR_ENDORSE_CHANGE";
	public static final String MOTOR_ENDORSE_ADDON = "MOTOR_ENDORSE_ADDON";

	/* Cargo Endorsement */
	public static final String CARGO_ENDORSE_INFO = "CARGO_ENDORSE_INFO";
	public static final String CHRGO_ENDORSE_SHIPVEHICLE = "CHRGO_ENDORSE_SHIPVEHICLE";
	public static final String CARGO_ENDORSE_PRODUCTINFO = "CARGO_ENDORSE_PRODUCTINFO";
	public static final String CARGO_ENDORSE_CHANGE = "CARGO_ENDORSE_CHANGE";
	public static final String CARGO_ENDORSE_ADDON = "CARGO_ENDORSE_ADDON";
	public static final String CARGO_POLICY_HISTORY_ATTACHMENT = "CARGO_POLICY_HISTORY_ATTACHMENT";
	public static final String CARGOPOLICYHISTORY_PRODUCTINFO = "CARGOPOLICYHISTORY_PRODUCTINFO";
	public static final String CARGOPOLICYHISTORYADDON = "CARGOPOLICYHISTORYADDON";
	public static final String CARGOPOLICYHISTORYKEYFACTOR = "CARGOPOLICYHISTORYKEYFACTOR";

	/* Cargo ProposalHistory */
	public static final String CARGOPROPOSAL_HISTORY = "CARGOPROPOSAL_HISTORY";
	public static final String SHIP_VEHICLEINFO_PROPOSAL_HISTORY = "SHIP_VEHICLEINFO_PROPOSAL_HISTORY";
	public static final String CARGOPROPOSAL_HISTORY_PRODUCTINFO = "CARGOPROPOSAL_HISTORY_PRODUCTINFO";
	public static final String CARGOPROPOSAL_HISTORY_ADDON = "CARGOPROPOSAL_HISTORY_ADDON";
	public static final String CARGOPROPOSAL_HISTORY_KEYFACTOR = "CARGOPROPOSAL_HISTORY_KEYFACTOR";
	public static final String CARGOPROPOSAL_ATTACHMENT_HISTORY = "CARGOPROPOSAL_ATTACHMENT_HISTORY";
	public static final String CARGOPROPOSAL_SHIPVEHICLE_ATTACHMENT_HISTORY = "CARGOPROPOSAL_SHIPVEHICLE_ATTACHMENT_HISTORY";

	/* Fire Endorsement */
	public static final String FIRE_ENDORSE_INFO = "FIRE_ENDORSE_INFO";
	public static final String FIRE_ENDORSE_BUILDING = "FIRE_ENDORSE_BUILDING";
	public static final String FIRE_ENDORSE_ENVBUILDING = "FIRE_ENDORSE_ENVBUILDING";
	public static final String FIRE_ENDORSE_PRODUCTINFO = "FIRE_ENDORSE_PRODUCTINFO";
	public static final String FIRE_ENDORSE_CHANGE = "FIRE_ENDORSE_CHANGE";
	public static final String FIRE_ENDORSE_ADDON = "FIRE_ENDORSE_ADDON";

	/* Fire Policy log */
	public static final String FIRE_POLICY_TIMELINE_LOG = "FIRE_POLICY_TIMELINE_LOG ";
	public static final String FIRE_POLICY_CLAIM_LOG = "FIRE_POLICY_CLAIM_LOG ";
	public static final String FIRE_POLICY_ENDORSE_LOG = "FIRE_POLICY_ENDORSE_LOG ";
	public static final String FIRE_POLICY_ID_LOG = "FIRE_POLICY_ID_LOG ";

	/* Cargo Policy Log */
	public static final String CARGO_POLICY_TIMELINE_LOG = "CARGO_POLICY_TIMELINE_LOG";
	public static final String CARGO_POLICY_ENDORSE_LOG = "CARGO_POLICY_ENDORSE_LOG";
	public static final String CARGO_POLICY_ID_LOG = "CARGO_POLICY_ID_LOG";

	/* Motor Policy log */
	public static final String MOTOR_POLICY_TIMELINE_LOG = "MOTOR_POLICY_TIMELINE_LOG ";
	public static final String MOTOR_POLICY_CLAIM_LOG = "MOTOR_POLICY_CLAIM_LOG ";
	public static final String MOTOR_POLICY_ENDORSE_LOG = "MOTOR_POLICY_ENDORSE_LOG ";
	public static final String MOTOR_POLICY_ID_LOG = "MOTOR_POLICY_ID_LOG ";

	/* Life Policy log */
	public static final String LIFE_POLICY_TIMELINE_LOG = "LIFE_POLICY_TIMELINE_LOG ";
	public static final String LIFE_POLICY_CLAIM_LOG = "LIFE_POLICY_CLAIM_LOG ";
	public static final String LIFE_POLICY_ENDORSE_LOG = "LIFE_POLICY_ENDORSE_LOG ";
	public static final String LIFE_POLICY_ID_LOG = "LIFE_POLICY_ID_LOG";

	/* Life Endorsement */
	public static final String LIFEENDORSEINFO = "LIFEENDORSEINFO";
	public static final String LIFEENDORSEINSUREDPERSON = "LIFEENDORSEINSUREDPERSON";
	public static final String LIFEENDORSECHANGE = "LIFEENDORSECHANGE";
	public static final String LIFEENDORSEBENEFICIARY = "LIFEENDORSEBENEFICIARY";

	public static final String POCLEARING_PAYMENT = "POCLEARING_PAYMENT";

	/* Travel Insurance */
	public static final String EXPRESS = "EXPRESS";
	public static final String TRAVELPROPOSAL = "TRAVELPROPOSAL";
	public static final String TRAVEL_EXPRESS = "TRAVEL_EXPRESS";
	public static final String EXPRESSDETAIL = "EXPRESS_DETAIL";
	public static final String TOUR = "TOUR";
	public static final String OCCURRENCE = "Occurrence";

	/* Person Travel Insurance */
	public static final String PERSONTRAVEL_PROPOSAL = "PERSONTRAVEL_PROPOSAL";
	public static final String PROPOSALTRAVELLER_BENEFICIARY = "PROPOSALTRAVELLER_BENEFICIARY";
	public static final String PERSONTRAVEL_PROPOSALINFO = "PERSONTRAVEL_PROPOSALINFO";
	public static final String PERSONTRAVEL_PROPOSAL_KEYFACTORVALUE = "PERSONTRAVEL_PROPOSAL_KEYFACTORVALUE";
	public static final String PROPOSALTRAVELLER = "PROPOSALTRAVELLER";
	public static final String PROPOSALPERSONTRAVEL_VEHICLE = "PROPOSALPERSONTRAVEL_VEHICLE";
	public static final String POLICYPERSONTRAVEL_VEHICLE = "POLICYPERSONTRAVEL_VEHICLE";

	public static final String PERSONTRAVEL_POLICY = "PERSONTRAVEL_POLICY";
	public static final String PERSONTRAVEL_POLICY_INFO = "PERSONTRAVEL_POLICY_INFO";
	public static final String POLICYTRAVELLER = "POLICYTRAVELLER";
	public static final String POLICYTRAVELLER_BENEFICIARY = "POLICYTRAVELLER_BENEFICIARY";
	public static final String PERSONTRAVEL_POLICY_KEYFACTORVALUE = "PERSONTRAVEL_POLICY_KEYFACTORVALUE";

	/* Motor Report */
	/* Motor Report */
	public static final String VWT_MOTOR_DAILYINCOME = "VWT_MOTOR_DAILYINCOME";
	public static final String VWT_MOTOR_PREMIUM_PAYMENT = "VWT_MOTOR_PREMIUM_PAYMENT";
	public static final String VWT_MOTORPROPOSAL = "VWT_MOTORPROPOSAL";
	public static final String VWT_MOTORRENEWALPROPOSAL = "VWT_MOTORRENEWALPROPOSAL";
	public static final String VWT_MOTORPROPOSAL_ENDORSEMENT = "VWT_MOTORPROPOSAL_ENDORSEMENT";
	public static final String VWT_MOTORTERMINATE_REGISTER = "VWT_MOTORTERMINATE_REGISTER";
	public static final String VWT_MOTORPOLICY = "VWT_MOTORPOLICY";
	public static final String VWT_MOTORCLAIM_REGISTER = "VWT_MOTORCLAIM_REGISTER";
	public static final String VWT_MOTORCLAIM_REPORT = "VWT_MOTORCLAIM_REPORT";
	public static final String VWT_MOTORCLAIM_PAYMENT = "VWT_MOTORCLAIM_PAYMENT";
	public static final String MOTOR_REINSTATEMENT = "VWT_MOTOR_REINSTATEMENT";
	public static final String VWT_MOTOR_MONTHLY_REPORT = "VWT_MOTOR_MONTHLY_REPORT";
	public static final String VWT_MOTOR_REINSTATEMENT = "VWT_MOTOR_REINSTATEMENT";
	public static final String VWT_MOTORENDORSEMENT_PAYMENT = "VWT_MOTORENDORSEMENT_PAYMENT";
	public static final String VWT_MOTORCLAIM_VEHICLE_REPORT = "VWT_MOTORCLAIM_VEHICLE_REPORT";
	public static final String VWT_MOTOR_ENDORSEMENT_REGISTER = "VWT_MOTOR_ENDORSEMENT_REGISTER";
	public static final String VWT_CARGOCLAIM_REGISTER = "VWT_CARGOCLAIM_REGISTER";
	public static final String VWT_CARGOCLAIM_PAYMENT = "VWT_CARGOCLAIM_PAYMENT";

	/* Fire Report */
	public static final String VWT_FIREPROPOSAL = "VWT_FIREPROPOSAL";
	public static final String VWT_FIREPOLICY = "VWT_FIREPOLICY";
	public static final String VWT_FIREPOLICYBUILDINGINFO = "VWT_FIREPOLICYBUILDINGINFO";
	public static final String VWT_FIRECLAIM = "VWT_FIRECLAIM_VIEW";
	public static final String VWT_FIRE_MONTHLY_REPORT = "VWT_FIRE_MONTHLY_REPORT";

	/* Agent Report */
	public static final String VW_REPORT_AGENT_COMMISSION_DETAIL = "VW_REPORT_AGENT_COMMISSION_DETAIL";
	public static final String AGENTSALE = "VWT_AGENTSALE";

	/* Life Report */
	public static final String VWT_LIFEPROPOSAL = "VWT_LIFEPROPOSAL";
	public static final String VWT_LIFEPOLICY = "VWT_LIFEPOLICY";
	public static final String VWT_LIFEDAILYINCOME = "VWT_FNI_LIFEDAILYINCOME";
	public static final String VWT_LIFE_MONTHLY_REPORT = "VWT_LIFE_MONTHLY_REPORT";
	public static final String VWT_LIFE_CLAIMREQUEST_REPORT = "VWT_LIFECLAIM_REQUEST_VIEW";
	public static final String VWT_LIFE_MONTHLY_RENEWAL_REPORT = "VWT_LIFE_MONTHLY_RENEWAL_REPORT";
	public static final String VWT_FNI_GROUP_LIFE_MONTHLY_INCOME = "VWT_FNI_GL_MONTHLY_INCOME";
	public static final String VWT_FNI_SNAKE_BITE_MONTHLY_INCOME = "VWT_FNI_SNB_MONTHLY_INCOME";
	public static final String VWT_FNI_UPR = "VWT_FNI_UPR_REPORT";
	/* Personal Accident Report */
	public static final String PERSONALACCIDENTPROPOSAL = "VWT_PERSONALACCIDENTPROPOSAL";
	public static final String VWT_PERSONALACCIDENTPOLICY = "VWT_PERSONALACCIDENTPOLICY";

	/* Farmer Monthly Report */
	public static final String FARMER_MONTHLY = "VWT_FARMER_MONTHLY_REPORT";
	public static final String PAMONTHLYINCOMEREPORT_VIEW = "VWT_FNI_PAMONTHLYINCOME";
	public static final String FARMERMONTHLYINCOMEREPORT_VIEW = "VWT_FNI_FARMERMONTHLYINCOME";

	/* Sale Point Income Report */
	public static final String VWT_FNI_SALEPOINTINCOME = "VWT_FNI_NEWSALEPOINTREPORT_VIEW";

	/* Medical */
	public static final String CUSTOMERSTATUS = "CUSTOMERINFOSTATUS";
	public static final String GUARDIAN = "MEDICALPROPOSAL_GUARDIAN";
	public static final String MPOLICYGUARDIAN = "MEDICALPOLICY_GUARDIAN";
	public static final String MEDICALPLACE = "MEDICALPLACE";
	public static final String ICD10 = "ICD10";
	public static final String OPERATION = "OPERATION";
	public static final String STATECODE = "STATECODE";
	public static final String TOWNSHIPCODE = "TOWNSHIPCODE";
	/* Medical proposal */
	public static final String MEDICALPROPOSAL = "MEDICALPROPOSAL";
	public static final String MEDICALPROPOSALTEMP = "MEDICALPROPOSAL_TEMP";
	public static final String MEDICALPROPOSALATTACHMENT = "MEDICALPROPOSAL_ATTACH_LINK";
	public static final String MEDICALPROPOSALINSUREDPERSON = "MEDICALPROPOSAL_INSUREDPERSON_LINK";
	public static final String MEDICALPROPOSALINSUREDPERSONATTACHMENT = "MEDICALPROPOSAL_INSUREDPERSON_ATTACH_LINK";
	public static final String MEDICALPROPOSALINSUREDPERSONADDON = "MEDICALPROPOSAL_INSUREDPERSON_ADDON_LINK";
	public static final String MEDICALPROPOSALINSUREDPERSONBENEFICIARIES = "MEDICALPROPOSAL_INSUREDPERSON_BENEFICIARIES_LINK";
	public static final String MEDICALKEYFACTORVALUE = "MEDICALKEYFACTORVALUE";
	public static final String MEDICALSURVEY = "MEDICALSURVEY";
	public static final String DEATHCLAIMSURVEY = "DEATHCLAIMSURVEY";
	public static final String MEDICALHISTORY = "MEDICALHISTORY";

	/* Medical policy */
	public static final String MEDICALPOLICY = "MEDICALPOLICY";
	public static final String MEDICALPOLICYATTACHMENT = "MEDICALPOLICY_ATTACH_LINK";
	public static final String MEDICALPOLICYINSUREDPERSON = "MEDICALPOLICY_INSUREDPERSON_LINK";
	public static final String MEDICALPOLICYINSUREDPERSONATTACHMENT = "MEDICALPOLICY_INSUREDPERSON_ATTACH_LINK";
	public static final String MEDICALPOLICYINSUREDPERSONADDON = "MEDICALPOLICY_INSUREDPERSON_ADDON_LINK";
	public static final String MEDICALPOLICYINSUREDPERSONBENEFICIARIES = "MEDICALPOLICY_INSUREDPERSON_BENEFICIARIES_LINK";
	public static final String MEDICALPOLICYKEYFACTORVALUE = "MEDICALPOLICY_KEYFACTORVALUE_LINK";
	public static final String MEDICALPOLICYMONTHLYREPORT = "VWT_MEDICALPOLICY_MONTHLYREPORT";
	public static final String VWT_MEDICAL_INSUREDPERSON_MONTHLY_REPORT = "VWT_MEDICALINSUREDPERSONMONTHLYREPORT";
	public static final String HEALTHDAILYREPORT_VIEW = "VWT_FNI_MEDICAL_DAILYINCOME_REPORT";
	public static final String HEALTHPROPOSALREPORT_VIEW = "VWT_HEALTH_PROPOSAL_REPORT";
	public static final String HEALTHPOLICYREPORT_VIEW = "VWT_HEALTH_POLICY_REPORT";
	public static final String MEDICAL_MONTHLY = "VWT_MEDICAL_MONTHLY";

	public static final String MEDPOLICY_EDITHISTORY = "MEDPOLICY_EDITHISTORY";
	public static final String MEDPOLICY_INSUREDPERSONBENEFICIARIES_EDITHISTORY = "MEDPOLICY_INSUREDPERSONBENEFICIARIES_EDITHISTORY_LINK";
	public static final String MEDPOLICY_INSUREDPERSON_EDITHISTORY = "MEDPOLICY_INSUREDPERSON_EDITHISTORY_LINK";

	/* Medical Claim */
	public static final String MEDICALCLAIM_ATTACHMENT = "MEDICALCLAIM_ATTACH_LINK";
	public static final String HOSPITALIZEDCLAIM_ATTACHMENT = "HOSPITALIZEDCLAIM_ATTACH_LINK";
	public static final String OPERATIONCLAIM_ATTACHMENT = "OPERATIONCLAIM_ATTACH_LINK";
	public static final String MEDICATIONCLAIM_ATTACHMENT = "MEDICINECLAIM_ATTACH_LINK";
	public static final String DEATHCLAIM_ATTACHMENT = "DEATHCLAIM_ATTACH_LINK";
	public static final String MEDICALCLAIM = "MEDICALCLAIM";
	public static final String MEDICALCLAIM_PROPOSAL = "MEDICALCLAIM_PROPOSAL";
	public static final String MEDICALCLAIM_INSUREDPERSON = "MEDICALCLAIM_INSUREDPERSON";
	public static final String MEDICALCLAIM_INSUREDPERSON_ATTACHMENT = "MEDICALCLAIM_INSUREDPERSON_ATTACH_LINK";
	public static final String MEDICALCLAIM_BENEFICIARY = "MEDICALCLAIM_BENEFICIARY_LINK";
	public static final String DEATHCLAIM = "DEATHCLAIM";
	public static final String HOSPITALIZEDCLAIM = "HOSPITALIZEDCLAIM";
	public static final String OPERATIONCLAIM = "OPERATIONCLAIM";
	public static final String MEDICATIONCLAIM = "MEDICATIONCLAIM";
	public static final String MEDICALCLAIMSURVEY = "MEDICALCLAIMSURVEY";
	public static final String CLAIM_INITIAL_REPORT = "CLAIM_INITIAL_REPORT";
	public static final String CLAIM_INITIAL_REPORT_ICD = "CLAIM_INITIAL_ICD";
	public static final String HOSPITALIZED_CLAIM_ICD = "HOSPITALIZED_CLAIM_ICD";
	public static final String DEATH_CLAIM_ICD = "DEATH_CLAIM_ICD";
	public static final String HEALTH_CLAIM_MONTHLY_REPORT = "VWT_HEALTH_CLAIM_MONTHLY_REPORT";
	/* Survey Question */
	public static final String PROCESS = "PROCESS";
	public static final String PRODUCTPROCESS = "PRODUCTPROCESS";
	public static final String RESOURCE_QUESTION_HISTORY = "RESOURCE_QUESTION_HISTORY";
	public static final String RESOURCEQUESTION = "RESOURCEQUESTION";
	public static final String PRODUCT_PROCESS_QUESTION_HISTORY = "PRODUCT_PROCESS_QUESTION_HISTORY";
	public static final String PRODUCT_PROCESS_QUESTION_LINK = "PRODUCT_PROCESS_QUESTION_LINK";
	public static final String SURVEYQUESTION = "SURVEYQUESTION";
	public static final String PRODUCTPROCESS_QUESTION_DETAIL_HISTORY = "PRODUCTPROCESS_QUESTION_DETAIL_HISTORY";
	public static final String SURVEYQUESTIONANSWER = "SURVEYQUESTIONANSWER";
	public static final String RESOURCEQUESTIONANSWER = "RESOURCEQUESTIONANSWER";

	/* Cargo Proposal */
	public static final String CARGOTYPE = "CARGOTYPE";
	public static final String CARGONAME = "CARGONAME";
	public static final String ROUTE = "ROUTE";
	public static final String CARGOSURVEY = "CARGOSURVEY";
	public static final String CARGOPROPOSAL = "CARGOPROPOSAL";
	public static final String SHIP_VEHICLEINFO_PROPOSAL = "SHIP_VEHICLEINFO_PROPOSAL";
	public static final String CARGOPROPOSAL_PRODUCTINFO = "CARGOPROPOSAL_PRODUCTINFO";
	public static final String CARGOPROPOSAL_ADDON = "CARGOPROPOSAL_ADDON";
	public static final String CARGOPROPOSAL_KEYFACTOR = "CARGOPROPOSAL_KEYFACTOR";

	/* Cargo Policy */
	public static final String CARGOPOLICY = "CARGOPOLICY";
	public static final String SHIPVEHICLEINFOPOLICY = "SHIPVEHICLEINFOPOLICY";
	public static final String CARGOPOLICYPRODUCTINFO = "CARGOPOLICYPRODUCTINFO";
	public static final String CARGOPOLICYKEYFACTOR = "CARGOPOLICYKEYFACTOR";
	public static final String CARGOPOLICYADDON = "CARGOPOLICYADDON";
	public static final String PORT = "PORT";

	/* Cargo Policy History */
	public static final String CARGOPOLICYHISTORY = "CARGOPOLICYHISTORY";
	public static final String SHIPVEHICLEINFOPOLICYHISTORY = "SHIPVEHICLEINFOPOLICYHISTORY";

	/* Marine Hull Proposal */
	public static final String MARINEHULLPROPOSAL = "MARINEHULLPROPOSAL";
	public static final String MARINEHULLINFO = "MARINEHULLINFO";
	public static final String MARINEHULL_ADDON = "MARINEHULL_ADDON";
	public static final String MARINEHULL_KEYFACTOR = "MARINEHULL_KEYFACTOR";
	public static final String MARINEHULLSURVEY = "MARINEHULLSURVEY";
	public static final String MARINEHULLPROPOSALATTACHMENT = "MARINEHULLPROPOSALATTACHMENT";
	public static final String MARINEHULLVESSELATTACHMENT = "MARINEHULLVESSELATTACHMENT";

	/* Marine Hull Policy */
	public static final String MARINEHULLPOLICY = "MARINEHULLPOLICY";
	public static final String MARINEHULLINFOPOLICY = "MARINEHULLINFOPOLICY";
	public static final String MARINEHULLPOLICYADDON = "MARINEHULLPOLICYADDON";
	public static final String MARINEHULLPOLICYKEYFACTOR = "MARINEHULLPOLICYKEYFACTOR";

	/* Report */
	public static final String VWT_CARGOPOLICY = "VWT_CARGOPOLICY";

	/* Cash In Safe Claim */
	public static final String CASHINSAFECLAIM = "CASHINSAFECLAIM";

	/* Cash In Safe Proposal */
	public static final String CASHINSAFESURVEY = "CISPROPOSAL_SURVEY_LINK";

	/* Cash In Transit Claim */
	public static final String CASHINTRANSIT_CLAIM = "CASHINTRANSIT_CLAIM";

	/* Travel Report */
	public static final String TRAVELDAILYINCOMEREPORT = "VWT_TRAVELDAILYINCOMEREPORT";
	public static final String TRAVELMONTHLYINCOMEREPORT = "VWT_TRAVELMONTHLYINCOMEREPORT";

	/* Travel Report */
	public static final String PERSONTRAVELMONTHLYINCOMEREPORT = "VWT_PERSONTRAVELMONTHLYINCOMEREPORT";

	/* Snake Bite Report */
	public static final String SNAKEBITEDAILYINCOMEREPORT = "VWT_SNAKEBITEDAILYINCOMEREPORT";

	/* Cargo Report */
	public static final String CARGOPROPOSALREPORT = "VWT_CARGOPROPOSAL";
	public static final String CARGOPOLICYREPORT = "VWT_CARGOPOLICYREPORT";
	public static final String CARGODAILYINCOMEREPORT = "VWT_CARGODAILYINCOMEREPORT";
	public static final String CARGOPREMIUMPAYMENTREPORT = "VWT_CARGOPREMIUMPAYMENTREPORT";
	public static final String CARGOMONTHLYREPORT = "VWT_CARGOMONTHLYREPORT";
	public static final String MARINEPAYMENTINFO = "VWT_MARINEPAYMENTINFO";

	/* Summary Report */
	public static final String LIFEPROPOSALSUMMARY = "VWT_LIFEPROPOSALSUMMARY";
	public static final String FIREPROPOSALSUMMARY = "VWT_FIREPROPOSALSUMMARY";
	public static final String MOTORPROPOSALSUMMARY = "VWT_MOTORPROPOSALSUMMARY";
	public static final String STAMPFEEREPORT = "VWT_STAMPFEEREPORT";

	/* CoInsurance Report */
	public static final String COINSURANCEREPORT = "VWT_COINSURANCEREPORT";
	public static final String COINSURANCESUMMARY = "VWT_COINSURANCESUMMARY";

	/* Fidelity Report */
	public static final String FIDELITYDAILYINCOMEREPORT = "VWT_FIDELITYDAILYINCOMEREPORT";
	public static final String FIDELITYMONTHLYREPORT = "VWT_FIDELITYMONTHLYREPORT";

	/* Cash In Safe Claim Report */
	public static final String VWT_CASHINSAFE_REPORT = "VWT_CASHINSAFE_REPORT";
	public static final String VWT_CASHINSAFEPROPOSAL = "VWT_CASHINSAFEPROPOSAL";

	/* Cash In Transit Proposal Daily Income Report */
	public static final String CASHINTRANSITDAILYINCOMEREPORT = "VWT_CASHINTRANSITDAILYINCOMEREPORT";
	public static final String VWT_CASHINTRANSIT_MONTHLY_REPORT = "VWT_CASHINTRANSIT_MONTHLY_REPORT";

	/* Cash In Transit Claim Daily Income Report */
	public static final String VWT_CASHINTRANSIT_CLAIM_DAILYINCOME = "VWT_CASHINTRANSIT_CLAIM_DAILYINCOME";
	public static final String VWT_CASHINTRANSIT_CLAIM_MONTHLY = "VWT_CASHINTRANSIT_CLAIM_MONTHLY";

	/* Agent report */
	public static final String VWT_AGENTSALEREPORT = "VWT_AGENTSALEREPORT";
	public static final String VWT_GENERAL_AGENT_SALE_REPORT = "VWT_GENERAL_AGENT_SALE_REPORT";
	public static final String VWT_LIFE_AGENT_SALE_REPORT = "VWT_LIFE_AGENT_SALE_REPORT";

	/* Customer Information report */
	public static final String VWT_CUSTOMER_INFORMATION_REPORT = "VWT_CUSTOMER_INFORMATION_REPORT";

	/* AutoRenewal */
	public static final String AUTORENEWAL = "AUTORENEWAL";

	/* Claim Product */
	public static final String CLAIMPRODUCT = "CLAIMPRODUCT";
	public static final String CLAIMPRODUCTRATE = "CLAIMPRODUCTRATE";
	public static final String CLAIMPRODUCTRATE_KEYFACTOR = "CLAIMPRODUCTRATE_KEYFACTOR";

	/* Life Surrender Proposal */
	public static final String LIFESURRENDERPROPOSAL = "LIFESURRENDERPROPOSAL";
	public static final String LIFESURRENDERKEYFACTOR = "LIFESURRENDERKEYFACTOR";

	/* Life PaidUp Proposal */
	public static final String LIFEPAIDUPPROPOSAL = "LIFEPAIDUPPROPOSAL";

	/* OverseasCargo Proposal */

	public static final String OVERSEASCARGOPROPOSAL = "OVERSEASCARGOPROPOSAL";
	public static final String OVERSEASPROPOSAL_VOYAGEINFO = "OVERSEASPROPOSAL_VOYAGEINFO";
	public static final String OVERSEASPROPOSAL_PRODUCTINFO = "OVERSEASPROPOSAL_PRODUCTINFO";
	public static final String PACKING = "PACKING";
	public static final String OVERSEASPROPOSAL_ADDON = "OVERSEASPROPOSAL_ADDON";
	public static final String OVERSEASPROPOSAL_KEYFACTOR = "OVERSEASPROPOSAL_KEYFACTOR";
	public static final String OVERSEASCARGOSURVEY = "OVERSEASCARGOSURVEY";

	/* OverseasCargo Policy */

	public static final String OVERSEASCARGOPOLICY = "OVERSEASCARGOPOLICY";
	public static final String OVERSEASPOLICY_VOYAGEINFO = "OVERSEASPOLICY_VOYAGEINFO";
	public static final String OVERSEASPOLICY_PRODUCTINFO = "OVERSEASPOLICY_PRODUCTINFO";
	public static final String OVERSEASPOLICY_ADDON = "OVERSEASPOLICY_ADDON";
	public static final String OVERSEASPOLICY_KEYFACTOR = "OVERSEASPOLICY_KEYFACTOR";

	public static final String MAINMENU = "MAINMENU";
	public static final String SUBMENU = "SUBMENU";
	public static final String MENUITEM = "MENUITEM";
	public static final String MAINMENUVALUE = "MAINMENUVALUE";
	public static final String SUBMENUVALUE = "SUBMENUVALUE";
	public static final String MENUITEMVALUE = "MENUITEMVALUE";

	/* Short Term Endowment Life Report */
	public static final String VWT_SHORTENDOWLIFEPOLICYVIEW = "VW_SHORTENDOWLIFEPOLICYVIEW";
	public static final String VWT_FNI_SHORTENDOWLIFEMONTHLYREPORTVIEW = "VWT_FNI_SHORTENDOWLIFEMONTHLYREPORTVIEW";

	/* Endownment Life Report */
	public static final String VWT_FNI_ENDOWNMENTLIFEMONTHLYREPORTVIEW = "VWT_FNI_ENDOWNMENTLIFEMONTHLYREPORTVIEW";

	/* Sport Man Life Report */
	public static final String VWT_FNI_SPORTMANMONTHLYREPORTVIEW = "VWT_FNI_SPORTMANMONTHLYREPORTVIEW";

	/* Sales Points */
	public static final String SALESPOINTS = "SALESPOINTS";

	/* Life and Medical salePoint Report */
	public static final String DAILYINCOMEREPORT_VIEW = "VWT_FNI_SALEPOINT_DAILYINCOME_REPORT_VIEW";
	public static final String ACCOUNTANDLIFEDEPTCANCELREPORT_VIEW = "VWT_FNI_ACCOUNTANDLIFEDEPT_CANCELREPORT_VIEW";
	public static final String MONTHLYINCOMEREPORT_VIEW = "VWT_FNI_MONTHLYINCOME";
	public static final String STUDENTMONTHLYINCOMEREPORT_VIEW = "VWT_FNI_STUDENTMONTHLYINCOMEREPORT_VIEW";

	/* Agent Job */
	public static final String SYSTEMJOBACTIVITY = "SYSTEMJOBACTIVITY";
	public static final String SYSJOBHISTORY = "SYSJOBHISTORY";
	public static final String SYSJOBS = "SYSJOBS";

	/* IBRB Report */
	public static final String VWT_FNI_HEALTH_IBRB_MONTHLY_REPORT = "VWT_FNI_HEALTH_IBRB_MONTHLY_REPORT";
	public static final String VWT_FNI_CRITICAL_ILLNESS_IBRB_MONTHLY_REPORT = "VWT_FNI_CRITICAL_ILLNESS_IBRB_MONTHLY_REPORT";
	public static final String VWT_FNI_MICRO_HEALTH_IBRB_MONTHLY_REPORT = "VWT_FNI_MICRO_HEALTH_IBRB_MONTHLY_REPORT";

	/* LIFEPOLICY TERMINATE */
	public static final String LIFEPOLICYTERMINATEINSUREDPERSONHISTORY = "LIFEPOLICYTERMINATEINSUREDPERSONHISTORY";
	public static final String LIFEPOLICYTERMINATEATTACHMENT = "LIFEPOLICYTERMINATE_ATTACH_LINK";
	public static final String LIFEPOLICYINSUREDPERSONTERMINATEBENEFICIARIES = "LIFEPOLICYTERMINATE_INSUREDPERSON_BENEFICIARIES_LINK";
	public static final String LIFEPOLICYTERMINATEINSUREDPERSONADDON = "LIFEPOLICYTERMINATE_INSUREDPERSON_ADDON_LINK";
	public static final String LIFEPOLICYTERMINATE_INSUREDPERSON = "LIFEPOLICYTERMINATE_INSUREDPERSON";
	public static final String LIFEPOLICYTERMINATEINSUREDPERSONATTACHMENT = "LIFEPOLICYTREMINATE_INSUREDPERSON_ATTACH_LINK";
	public static final String LIFEPOLICYTERMINATEINSUREDPERSONKEYFACTOR = "LIFEPOLICYTERMINATE_INSUREDPERSON_KEYFACTORVALUE_LINK";
	public static final String POLICYTERMINATION = "POLICYTERMINATION";

	/* MEDICALPOLICY TERMINATE */
	public static final String MPOLICYGUARDIAN_TERMINATE = "MPOLICYGUARDIAN_TERMINATE";
	public static final String MEDICALPOLICYATTACHMENT_TERMINATE = "MEDICALPOLICYATTACHMENT_TERMINATE";

	public static final String MEDPOLICY_TERMINATE = "MEDPOLICY_TERMINATE";
	public static final String PERSONPRODUCTHISTORYTERMINATE = "PERSONPRODUCTHISTORY_TERMINATE";

	public static final String MEDICALPOLICYINSUREDPERSONATTACHMEN_TTERMINATE = "MEDICALPOLICYINSUREDPERSONATTACHMEN_TTERMINATE";
	public static final String MEDICALPOLICYINSUREDPERSONADDON_TERMINATE = "MEDICALPOLICYINSUREDPERSONADDON_TERMINATE";

	public static final String MEDICALPOLICYKEYFACTORVALUE_TERMINATE = "MEDICALPOLICYKEYFACTORVALUE_TERMINATE";
	public static final String MEDPOLICY_INSUREDPERSONBENEFICIARIES_TERMINATE = "MEDPOLICY_INSUREDPERSONBENEFICIARIES_TERMINATE";

	public static final String MEDICALPERSONHISTORYRECORD_TERMINATE = "MEDICALPERSONHISTORYRECORD_TERMINATE";
	public static final String MEDPOLICY_INSUREDPERSON_TERMINATE = "MEDPOLICY_INSUREDPERSON_TERMINATE";
	public static final String LIFEPOLICYTERMINATEINSUREDPERSONBENEFICIARIES = "LIFEPOLICYTERMINATEINSUREDPERSONBENEFICIARIES";

	/* STUDENT LIFE */
	public static final String GRADEINFO = "GRADEINFO";
	public static final String INSURANCE_HISTORY_RECORD = "INSURANCE_HISTORY_RECORD";
	public static final String SCHOOL = "SCHOOL";

	/* Log Table */
	public static final String USERLOG = "USERLOG";

	public static final String AUTHORITYPERMISSION = "AUTHORITYPERMISSION";

	public static final String DISABILITYPART = "DISABILITYPART";

	public static final String LIFECLAIMMONTHLYREPORT_VIEW = "VWT_LIFECLAIMMONTHLYREPORT";

	/* Farmer Proposal */
	public static final String FARMERPROPOSAL = "FARMERPROPOSAL";
	public static final String FARMERPROPOSAL_ATTACH_LINK = "FARMERPROPOSAL_ATTACH_LINK";
}